spring.application.name=valoracion
server.port=8088

spring.datasource.url=jdbc:mysql://localhost:3306/valoracion_db
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
